$(function(){
	'use-strict';

	AOS.init({
	 	once: true,
	 	duration: 1500,
	});
	
});
function ciyanalog(){
	console.log("                  :i7r::i                                                                           \n                r..:...  .                                                                          \n           ..iPRq:.   iSrBj.                                                                        \n     .::ir::UEjU:      EvL1                                                                         \n  7jj7:iS. DU:..i7Y7: 7I:..  .v.                                                                    \n iD    : v7.:     .r2ui::  v7J7u                                                                    \n  vsrii Xg r   iuB::i::s1  v77Y7P                                                                   \n    2: db rXsjJsis:..   JX  uvi.                                                             .      \n   r. 5D r.              vs..   i:      .Y:          ii.:irii    .s.    .:iiii.         .:::iirr:   \n  r: 7Q :r               ::::   v.7     i::i     ..rggrsUY1:.7   r::i.:iv2jus r:      .qX.ijsvU.:i  \n  7 PQd J                ri5:. i.bii    rivi.   i:XDr7U:  i J:7  7.7.i752:  ::rr.  .:rQu:jL.  r Pr. \n :. Eg r:        .Y21s  :.Qr:  r.E.r   i.B:r  .i 7I.r:    .vQ.: :.b5 II.   r B:r  :::Q..r.   i KXi. \n:. .B  s        vEi  7P.:iB r r Q r    :LD r .r:BL 7     r B.i  r.B Ji    .::7.: :::D :r     i.B.i  \nv  vD .v       7b     ub B.i  :vZ.:   r.B i  v BB.r     ..LP.. r dr:.     7 B.r .i 2 .7     i Pr.   \nJ  jP ii       Ks     K.7g i r B.r   7.15 : 7. 1 :.     r B.r .i.r.r     :.1q.. v PX v     ::rB : i \n:. LD ir       r2    su X.r ..jX.. .Ii B 7.sv 5r 7    rU I5:  7 Bir      7 B.7 .r Q..i   .2v B5L1urL\n .. B :r            7u sv.: r.B i s1.:BB.qY:7 Mv.   rIY .B.i .:vg.i     i.1J:.  r B r   YSr vb 5U .v\n  7.YQ 7           7ri g.r  :7v.SJi:.:B:r   .i7g:irILir.7si  i R.7      v.u.r   5.Q:riYU7ii d.7   q.\n   i.uDr7       .isr::7 i.  J: ii..Y D:..     :7:Lvi:. r..:  iu r.      .7 7  .qr.7::s7i: .7 i. .P7 \n    ..rZdLKr:r7sL7:.   rj7ruYi ..rJ::Q r        ..      ijr:J2ii1        :rU:JX:   ...     .rUijK:  \n        .iUiri:.        ...   .7j.7.B.r                  .rr:   .          .r:               .r.    \n                            :5j:  :.r::                                                             \n                          i5j.   i.Q.7                                                              \n                        .qu.    .:IX:.                                                              \n                       iP.      r.B::                                                               \n                     :22.     :r:Br:                                                                \n                     :QIv:..rsL2B7.                                                                 \n                        .rri.  r                                                                    ");
}